In [18]:
import numpy as np
import pandas as pd

In [19]:
df = pd.read_csv('Dataset_Dec.csv')

In [20]:
df.head()

Area  Year                Item  Area Harvested   Yield  Production
0  Bangladesh  1961          Areca nuts           82600    7627       62995
1  Bangladesh  1961             Bananas           33600  132738      446000
2  Bangladesh  1961              Barley           29947    5768       17272
3  Bangladesh  1961  Bastfibres, others           30900   11117       34350
4  Bangladesh  1961          Beans, dry           68798    7236       49784

In [21]:
df['Item'].nunique()

54

In [22]:
pd.get_dummies(df,columns=['Area','Item'])

Year  Area Harvested    Yield  Production  Area_Bangladesh  \
0     1961           82600     7627       62995                1   
1     1961           33600   132738      446000                1   
2     1961           29947     5768       17272                1   
3     1961           30900    11117       34350                1   
4     1961           68798     7236       49784                1   
...    ...             ...      ...         ...              ...   
3180  2019           28205   137441      387653                1   
3181  2019          227884    89272     2034364                1   
3182  2019          330348  1016811       30780                1   
3183  2019          491409   201278     9890963                1   
3184  2019          651132    96768     6300864                1   

      Item_Areca nuts  Item_Bananas  Item_Barley  Item_Bastfibres, others  \
0                   1             0            0                        0   
1                   0             1            0                        0   
2                   0             0            1                        0   
3                   0             0            0                        1   
4                   0             0            0                        0   
...               ...           ...          ...                      ...   
3180                0             0            0                        0   
3181                0             0            0                        0   
3182                0             0            0                        0   
3183                0             0            0                        0   
3184                0             0            0                        0   

      Item_Beans, dry  ...  Item_Sugar cane  Item_Sugar crops nes  \
0                   0  ...                0                     0   
1                   0  ...                0                     0   
2                   0  ...                0                     0   
3                   0  ...                0                     0   
4                   1  ...                0                     0   
...               ...  ...              ...                   ...   
3180                0  ...                0                     0   
3181                0  ...                0                     0   
3182                0  ...                0                     0   
3183                0  ...                0                     0   
3184                0  ...                0                     0   

      Item_Sweet potatoes  Item_Tangerines, mandarins, clementines, satsumas  \
0                       0                                                  0   
1                       0                                                  0   
2                       0                                                  0   
3                       0                                                  0   
4                       0                                                  0   
...                   ...                                                ...   
3180                    0                                                  0   
3181                    0                                                  0   
3182                    0                                                  0   
3183                    0                                                  0   
3184                    0                                                  0   

      Item_Tea  Item_Tobacco  Item_Tomatoes  Item_Vegetables Primary  \
0            0             0              0                        0   
1            0             0              0                        0   
2            0             0              0                        0   
3            0             0              0                        0   
4            0             0              0                        0   
...        ...           ...            ..

In [23]:
pd.get_dummies(df,columns=['Area','Item'],drop_first=True)

Year  Area Harvested    Yield  Production  Item_Bananas  Item_Barley  \
0     1961           82600     7627       62995             0            0   
1     1961           33600   132738      446000             1            0   
2     1961           29947     5768       17272             0            1   
3     1961           30900    11117       34350             0            0   
4     1961           68798     7236       49784             0            0   
...    ...             ...      ...         ...           ...          ...   
3180  2019           28205   137441      387653             0            0   
3181  2019          227884    89272     2034364             0            0   
3182  2019          330348  1016811       30780             0            0   
3183  2019          491409   201278     9890963             0            0   
3184  2019          651132    96768     6300864             0            0   

      Item_Bastfibres, others  Item_Beans, dry  Item_Beans, green  \
0                           0                0                  0   
1                           0                0                  0   
2                           0                0                  0   
3                           1                0                  0   
4                           0                1                  0   
...                       ...              ...                ...   
3180                        0                0                  0   
3181                        0                0                  0   
3182                        0                0                  0   
3183                        0                0                  0   
3184                        0                0                  0   

      Item_Berries nes  ...  Item_Sugar cane  Item_Sugar crops nes  \
0                    0  ...                0                     0   
1                    0  ...                0                     0   
2                    0  ...                0                     0   
3                    0  ...                0                     0   
4                    0  ...                0                     0   
...                ...  ...              ...                   ...   
3180                 0  ...                0                     0   
3181                 0  ...                0                     0   
3182                 0  ...                0                     0   
3183                 0  ...                0                     0   
3184                 0  ...                0                     0   

      Item_Sweet potatoes  Item_Tangerines, mandarins, clementines, satsumas  \
0                       0                                                  0   
1                       0                                                  0   
2                       0                                                  0   
3                       0                                                  0   
4                       0                                                  0   
...                   ...                                                ...   
3180                    0                                                  0   
3181                    0                                                  0   
3182                    0                                                  0   
3183                    0                                                  0   
3184                    0                                                  0   

      Item_Tea  Item_Tobacco  Item_Tomatoes  Item_Vegetables Primary  \
0            0             0              0                        0   
1            0             0              0                        0   
2            0             0              0                        0   
3            0             0              0                        0   
4            0             0              0                        0   
...   

In [24]:
from sklearn.model_selection import train_test_split
# first 5 cols as train as input, last col as output
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:5],df.iloc[:,-1],test_size=0.2,random_state=2)

In [25]:
X_test.head()

Area  Year          Item  Area Harvested  Yield
3064  Bangladesh  2017    Spices nes           47332  35494
761   Bangladesh  1975  Beans, green            6632  39704
2692  Bangladesh  2010           Tea           52236  11486
2940  Bangladesh  2015       Linseed            7009   6941
1901  Bangladesh  1996      Coconuts           29200  30479

In [26]:
from sklearn.preprocessing import OneHotEncoder

In [27]:
# object
# multicollinearity removal
# removing the catagories from the columns with drop first
ohe = OneHotEncoder(drop='first',sparse=False,dtype=np.int32)

In [28]:
X_train_new = ohe.fit_transform(X_train[['Area','Item']])
# we get the no. of cols depending on the categories
X_train_new

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [29]:
X_test_new = ohe.transform(X_test[['Area','Item']])

In [30]:
X_test_new

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]])

In [31]:
data = np.hstack((X_train[['Year','Area Harvested','Yield']].values,X_train_new))
data

array([[    2008,    72581,     9856, ...,        0,        0,        0],
       [    2011,   708723,    21494, ...,        0,        0,        0],
       [    1985,    77023,    62181, ...,        0,        1,        0],
       ...,
       [    1990,     4014,    45279, ...,        0,        0,        0],
       [    2008,    46482,     8547, ...,        0,        0,        0],
       [    2008, 11279150,    41441, ...,        0,        0,        0]],
      dtype=int64)

In [32]:
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

In [33]:
x = data[:, :-1]
y = data[:,5]
X_train_new, X_test_new, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [35]:
from kmodes.kprototypes import KPrototypes
kproto = KPrototypes(n_clusters=2, verbose=2, max_iter=20)
#kproto.fit(df_array, categorical=cat_idx)
print(kproto.cluster_centroids_)

AttributeError: '{}' object has no attribute 'cluster_centroids_' because the model is not yet fitted.

###  Evaluation of the model

#### R-Squared


In [20]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, predict_production)
print(r2)

-0.18055555555555514


#### Mean Absolute Error

In [21]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, predict_production)

0.013725490196078431

#### AUC-ROC Curve

In [22]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test, predict_production)

0.746031746031746

#### Confusion Matrix related Metrices

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score, f1_score, classification_report
cm = confusion_matrix(y_test, predict_production)
ac = accuracy_score(y_test, predict_production)
rs = recall_score(y_test, predict_production)
pr = precision_score(y_test, predict_production)
f1 = f1_score(y_test, predict_production, average=None)

In [24]:
# Confusion Matrix
print (cm)

[[500   4]
 [  3   3]]


In [25]:
# Accuracy Score
print (ac)

0.9862745098039216


In [26]:
# Recall Score
print (rs)

0.5


In [27]:
# Precision Score
print (pr)

0.42857142857142855


In [28]:
# F1 Score
print (f1)

[0.99304866 0.46153846]


#### Classification Report 

In [29]:
# report
print(classification_report(y_test, predict_production, target_names=None))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       504
           1       0.43      0.50      0.46         6

    accuracy                           0.99       510
   macro avg       0.71      0.75      0.73       510
weighted avg       0.99      0.99      0.99       510

