In [37]:
pwd

'C:\\Users\\DELL\\OneDrive\\Desktop\\Crop-Yield-Prediction-BD'

In [38]:
import numpy as np
import pandas as pd
df=pd.read_csv("C:\\Users\\DELL\\OneDrive\\Desktop\\Crop-Yield-Prediction-BD\\Dataset_Jan.csv")
df

Area  Year                   Item  Area Harvested    Yield  \
0     Bangladesh  1961             Areca nuts           82600     7627   
1     Bangladesh  1961                Bananas           33600   132738   
2     Bangladesh  1961                 Barley           29947     5768   
3     Bangladesh  1961     Bastfibres, others           30900    11117   
4     Bangladesh  1961             Beans, dry           68798     7236   
...          ...   ...                    ...             ...      ...   
3180  Bangladesh  2019               Tomatoes           28205   137441   
3181  Bangladesh  2019  Vegetables, fresh nes          227884    89272   
3182  Bangladesh  2019                  Wheat          330348  1016811   
3183  Bangladesh  2019       Roots and Tubers          491409   201278   
3184  Bangladesh  2019     Vegetables Primary          651132    96768   

      Humidity  Wind Speed  Temperature  Production  
0          NaN         NaN          NaN       62995  
1          NaN         NaN          NaN      446000  
2          NaN         NaN          NaN       17272  
3          NaN         NaN          NaN       34350  
4          NaN         NaN          NaN       49784  
...        ...         ...          ...         ...  
3180     15.81      153.56         25.9      387653  
3181     15.81      153.56         25.9     2034364  
3182     15.81      153.56         25.9       30780  
3183     15.81      153.56         25.9     9890963  
3184     15.81      153.56         25.9     6300864  

[3185 rows x 9 columns]

In [39]:
df.head()

Area  Year                Item  Area Harvested   Yield  Humidity  \
0  Bangladesh  1961          Areca nuts           82600    7627       NaN   
1  Bangladesh  1961             Bananas           33600  132738       NaN   
2  Bangladesh  1961              Barley           29947    5768       NaN   
3  Bangladesh  1961  Bastfibres, others           30900   11117       NaN   
4  Bangladesh  1961          Beans, dry           68798    7236       NaN   

   Wind Speed  Temperature  Production  
0         NaN          NaN       62995  
1         NaN          NaN      446000  
2         NaN          NaN       17272  
3         NaN          NaN       34350  
4         NaN          NaN       49784

In [40]:
# df['Item'].value_counts()
df['Item'].nunique()

54

In [41]:
df.shape

(3185, 9)

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3185 entries, 0 to 3184
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Area            3185 non-null   object 
 1   Year            3185 non-null   int64  
 2   Item            3185 non-null   object 
 3   Area Harvested  3185 non-null   int64  
 4   Yield           3185 non-null   int64  
 5   Humidity        2105 non-null   float64
 6   Wind Speed      2105 non-null   float64
 7   Temperature     2105 non-null   float64
 8   Production      3185 non-null   int64  
dtypes: float64(3), int64(4), object(2)
memory usage: 224.1+ KB


In [43]:
mean_temp=df['Temperature'].mean()
mean_hum=df['Humidity'].mean()
mean_wind=df['Wind Speed'].mean()
df['Temperature'].fillna(value=mean_temp, inplace=True)
df['Humidity'].fillna(value=mean_hum, inplace=True)
df['Wind Speed'].fillna(value=mean_wind, inplace=True)

In [44]:
df.head()

Area  Year                Item  Area Harvested   Yield   Humidity  \
0  Bangladesh  1961          Areca nuts           82600    7627  14.404385   
1  Bangladesh  1961             Bananas           33600  132738  14.404385   
2  Bangladesh  1961              Barley           29947    5768  14.404385   
3  Bangladesh  1961  Bastfibres, others           30900   11117  14.404385   
4  Bangladesh  1961          Beans, dry           68798    7236  14.404385   

   Wind Speed  Temperature  Production  
0   162.94838    26.311311       62995  
1   162.94838    26.311311      446000  
2   162.94838    26.311311       17272  
3   162.94838    26.311311       34350  
4   162.94838    26.311311       49784

In [45]:
from sklearn.model_selection import train_test_split
# first 5 cols as train as input, last col as output
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:8],df.iloc[:,-1],test_size=0.2,random_state=2)

In [46]:
X_test.head()

Area  Year          Item  Area Harvested  Yield   Humidity  \
3064  Bangladesh  2017    Spices nes           47332  35494  16.420000   
761   Bangladesh  1975  Beans, green            6632  39704  14.404385   
2692  Bangladesh  2010           Tea           52236  11486  15.500000   
2940  Bangladesh  2015       Linseed            7009   6941  15.440000   
1901  Bangladesh  1996      Coconuts           29200  30479  13.000000   

      Wind Speed  Temperature  
3064   170.19000    25.360000  
761    162.94838    26.311311  
2692   172.75000    26.020000  
2940   188.19000    25.920000  
1901   174.75000    28.000000

In [47]:
from sklearn.preprocessing import OneHotEncoder

In [48]:
# object
# multicollinearity removal
# removing the catagories from the columns with drop first
ohe = OneHotEncoder(drop='first',sparse=False,dtype=np.int32)

In [49]:
X_train_new = ohe.fit_transform(X_train[['Item']])
# we get the no. of cols depending on the categories
X_train_new

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [50]:
X_test_new = ohe.transform(X_test[['Item']])

In [51]:
X_test_new

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]])

In [52]:
# now to append everything together
data = np.hstack((X_train[['Year','Area Harvested','Yield','Humidity','Wind Speed','Temperature']].values,X_train_new))
data

array([[2.008000e+03, 7.258100e+04, 9.856000e+03, ..., 0.000000e+00,
        0.000000e+00, 0.000000e+00],
       [2.011000e+03, 7.087230e+05, 2.149400e+04, ..., 0.000000e+00,
        0.000000e+00, 0.000000e+00],
       [1.985000e+03, 7.702300e+04, 6.218100e+04, ..., 0.000000e+00,
        1.000000e+00, 0.000000e+00],
       ...,
       [1.990000e+03, 4.014000e+03, 4.527900e+04, ..., 0.000000e+00,
        0.000000e+00, 0.000000e+00],
       [2.008000e+03, 4.648200e+04, 8.547000e+03, ..., 0.000000e+00,
        0.000000e+00, 0.000000e+00],
       [2.008000e+03, 1.127915e+07, 4.144100e+04, ..., 0.000000e+00,
        0.000000e+00, 0.000000e+00]])

# Naive Bayes

In [54]:
x = data[:,0:5]
y = data[:,-1]
X_train_new, X_test_new, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [55]:
# Training the Naive Bayes model on the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train_new, y_train)

GaussianNB()

In [56]:
# Predicting the Test set results
y_pred = classifier.predict(X_test_new)

In [57]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
ac = accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test, y_pred)

In [58]:
#Accuracy
print(ac)

0.9725490196078431


In [59]:
#Confusion Matrix
print(cm)

[[487  10]
 [  4   9]]


In [60]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred)

0.027450980392156862

In [61]:
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score, f1_score, classification_report
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test, y_pred)
rs = recall_score(y_test, y_pred)
pr = precision_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average=None)

In [62]:
# Recall Score
print (rs)

0.6923076923076923


In [63]:
# Precision Score
print (pr)

0.47368421052631576


In [64]:
# F1 Score
print (f1)

[0.98582996 0.5625    ]
