In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('Dataset_Jan.csv')

In [3]:
df.head()

Area  Year                Item  Area Harvested   Yield  Humidity  \
0  Bangladesh  1961          Areca nuts           82600    7627       NaN   
1  Bangladesh  1961             Bananas           33600  132738       NaN   
2  Bangladesh  1961              Barley           29947    5768       NaN   
3  Bangladesh  1961  Bastfibres, others           30900   11117       NaN   
4  Bangladesh  1961          Beans, dry           68798    7236       NaN   

   Wind Speed  Temperature  Production  
0         NaN          NaN       62995  
1         NaN          NaN      446000  
2         NaN          NaN       17272  
3         NaN          NaN       34350  
4         NaN          NaN       49784

In [4]:
df.tail()

Area  Year                   Item  Area Harvested    Yield  \
3180  Bangladesh  2019               Tomatoes           28205   137441   
3181  Bangladesh  2019  Vegetables, fresh nes          227884    89272   
3182  Bangladesh  2019                  Wheat          330348  1016811   
3183  Bangladesh  2019       Roots and Tubers          491409   201278   
3184  Bangladesh  2019     Vegetables Primary          651132    96768   

      Humidity  Wind Speed  Temperature  Production  
3180     15.81      153.56         25.9      387653  
3181     15.81      153.56         25.9     2034364  
3182     15.81      153.56         25.9       30780  
3183     15.81      153.56         25.9     9890963  
3184     15.81      153.56         25.9     6300864

In [7]:
# df['Item'].value_counts()
df['Item'].nunique()

54

In [8]:
df.shape

(3185, 9)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3185 entries, 0 to 3184
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Area            3185 non-null   object 
 1   Year            3185 non-null   int64  
 2   Item            3185 non-null   object 
 3   Area Harvested  3185 non-null   int64  
 4   Yield           3185 non-null   int64  
 5   Humidity        2105 non-null   float64
 6   Wind Speed      2105 non-null   float64
 7   Temperature     2105 non-null   float64
 8   Production      3185 non-null   int64  
dtypes: float64(3), int64(4), object(2)
memory usage: 224.1+ KB


In [10]:
mean_temp=df['Temperature'].mean()
mean_hum=df['Humidity'].mean()
mean_wind=df['Wind Speed'].mean()
df['Temperature'].fillna(value=mean_temp, inplace=True)
df['Humidity'].fillna(value=mean_hum, inplace=True)
df['Wind Speed'].fillna(value=mean_wind, inplace=True)

In [11]:
df.head()

Area  Year                Item  Area Harvested   Yield   Humidity  \
0  Bangladesh  1961          Areca nuts           82600    7627  14.404385   
1  Bangladesh  1961             Bananas           33600  132738  14.404385   
2  Bangladesh  1961              Barley           29947    5768  14.404385   
3  Bangladesh  1961  Bastfibres, others           30900   11117  14.404385   
4  Bangladesh  1961          Beans, dry           68798    7236  14.404385   

   Wind Speed  Temperature  Production  
0   162.94838    26.311311       62995  
1   162.94838    26.311311      446000  
2   162.94838    26.311311       17272  
3   162.94838    26.311311       34350  
4   162.94838    26.311311       49784

## OneHotEncoding using sklearn

In [12]:
from sklearn.model_selection import train_test_split
# first 8 cols as train as input, last col as output
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:8],df.iloc[:,-1],test_size=0.2,random_state=2)

In [14]:
X_train.head()

Area  Year                   Item  Area Harvested   Yield  \
2560  Bangladesh  2008                Lentils           72581    9856   
2720  Bangladesh  2011                   Jute          708723   21494   
1346  Bangladesh  1985  Vegetables, fresh nes           77023   62181   
148   Bangladesh  1963                Sorghum             809   12559   
2473  Bangladesh  2006        Sugar crops nes           20234  191756   

       Humidity  Wind Speed  Temperature  
2560  15.080000   151.06000    25.570000  
2720  15.010000   143.19000    25.600000  
1346  13.120000   157.88000    27.690000  
148   14.404385   162.94838    26.311311  
2473  15.080000   131.94000    25.570000

In [15]:
from sklearn.preprocessing import OneHotEncoder

In [16]:
# object
# multicollinearity removal
# removing the catagories from the columns with drop first
ohe = OneHotEncoder(drop='first',sparse=False,dtype=np.int32)

In [17]:
X_train_new = ohe.fit_transform(X_train[['Item']])
# we get the no. of cols depending on the categories
X_train_new

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [18]:
X_test_new = ohe.transform(X_test[['Item']])

In [19]:
X_test_new

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]])

In [20]:
# now to append everything together
data = np.hstack((X_train[['Year','Area Harvested','Yield','Humidity','Wind Speed','Temperature']].values,X_train_new))
data

array([[2.008000e+03, 7.258100e+04, 9.856000e+03, ..., 0.000000e+00,
        0.000000e+00, 0.000000e+00],
       [2.011000e+03, 7.087230e+05, 2.149400e+04, ..., 0.000000e+00,
        0.000000e+00, 0.000000e+00],
       [1.985000e+03, 7.702300e+04, 6.218100e+04, ..., 0.000000e+00,
        1.000000e+00, 0.000000e+00],
       ...,
       [1.990000e+03, 4.014000e+03, 4.527900e+04, ..., 0.000000e+00,
        0.000000e+00, 0.000000e+00],
       [2.008000e+03, 4.648200e+04, 8.547000e+03, ..., 0.000000e+00,
        0.000000e+00, 0.000000e+00],
       [2.008000e+03, 1.127915e+07, 4.144100e+04, ..., 0.000000e+00,
        0.000000e+00, 0.000000e+00]])

## SVM

In [21]:
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC

In [22]:
x = data[:,0:8]
y = data[:,-1]
X_train_new, X_test_new, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [23]:
x

array([[2.008000e+03, 7.258100e+04, 9.856000e+03, ..., 2.557000e+01,
        0.000000e+00, 0.000000e+00],
       [2.011000e+03, 7.087230e+05, 2.149400e+04, ..., 2.560000e+01,
        0.000000e+00, 0.000000e+00],
       [1.985000e+03, 7.702300e+04, 6.218100e+04, ..., 2.769000e+01,
        0.000000e+00, 0.000000e+00],
       ...,
       [1.990000e+03, 4.014000e+03, 4.527900e+04, ..., 2.733000e+01,
        0.000000e+00, 0.000000e+00],
       [2.008000e+03, 4.648200e+04, 8.547000e+03, ..., 2.557000e+01,
        0.000000e+00, 0.000000e+00],
       [2.008000e+03, 1.127915e+07, 4.144100e+04, ..., 2.557000e+01,
        0.000000e+00, 0.000000e+00]])

In [116]:
model = SVC()
model.fit(X_train_new,y_train)
predict_production = model.predict(X_test_new)
print("Accuracy: ",accuracy_score(y_test, predict_production))

Accuracy:  0.9803921568627451


## Evaluation of the model

#### R-Squared

In [117]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, predict_production)
print(r2)

0.3914807302231236


#### Mean Absolute Error (MAE)

In [118]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, predict_production)

0.0196078431372549

#### Mean squared error

In [119]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, predict_production)

0.0196078431372549

#### AUC-ROC Curve

In [120]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test, predict_production)

0.7058823529411764

#### Confusion Matrix and related Metrics

In [121]:
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score, f1_score, classification_report
cm = confusion_matrix(y_test, predict_production)
ac = accuracy_score(y_test, predict_production)
rs = recall_score(y_test, predict_production)
pr = precision_score(y_test, predict_production)
f1 = f1_score(y_test, predict_production, average=None)

In [122]:
# Confusion Matrix
print (cm)

[[493   0]
 [ 10   7]]


In [123]:
# Accuracy Score
print (ac)

0.9803921568627451


In [124]:
# Recall Score
print (rs)

0.4117647058823529


In [125]:
# Precision Score
print (pr)

1.0


In [126]:
# F1 Score
print (f1)

[0.98995984 0.58333333]


#### Classification Report

In [127]:
# report
print(classification_report(y_test, predict_production, target_names=None))

              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99       493
         1.0       1.00      0.41      0.58        17

    accuracy                           0.98       510
   macro avg       0.99      0.71      0.79       510
weighted avg       0.98      0.98      0.98       510

