In [1]:
pwd

'C:\\Users\\DELL\\OneDrive\\Desktop\\Crop-Yield-Prediction-BD'

#Reading Dataset

In [3]:
import numpy as np
import pandas as pd
df=pd.read_csv("C:\\Users\\DELL\\OneDrive\\Desktop\\Crop-Yield-Prediction-BD\\Dataset_Dec.csv")
df

Area  Year                   Item  Area Harvested    Yield  \
0     Bangladesh  1961             Areca nuts           82600     7627   
1     Bangladesh  1961                Bananas           33600   132738   
2     Bangladesh  1961                 Barley           29947     5768   
3     Bangladesh  1961     Bastfibres, others           30900    11117   
4     Bangladesh  1961             Beans, dry           68798     7236   
...          ...   ...                    ...             ...      ...   
3180  Bangladesh  2019               Tomatoes           28205   137441   
3181  Bangladesh  2019  Vegetables, fresh nes          227884    89272   
3182  Bangladesh  2019                  Wheat          330348  1016811   
3183  Bangladesh  2019       Roots and Tubers          491409   201278   
3184  Bangladesh  2019     Vegetables Primary          651132    96768   

      Production  
0          62995  
1         446000  
2          17272  
3          34350  
4          49784  
...          ...  
3180      387653  
3181     2034364  
3182       30780  
3183     9890963  
3184     6300864  

[3185 rows x 6 columns]

In [4]:
df.head()

Area  Year                Item  Area Harvested   Yield  Production
0  Bangladesh  1961          Areca nuts           82600    7627       62995
1  Bangladesh  1961             Bananas           33600  132738      446000
2  Bangladesh  1961              Barley           29947    5768       17272
3  Bangladesh  1961  Bastfibres, others           30900   11117       34350
4  Bangladesh  1961          Beans, dry           68798    7236       49784

In [5]:
df['Item'].nunique()

54

In [14]:
## One hot encoding using pandas

In [15]:
pd.get_dummies(df,columns=['Area','Item'])

Year  Area Harvested    Yield  Production  Area_Bangladesh  \
0     1961           82600     7627       62995                1   
1     1961           33600   132738      446000                1   
2     1961           29947     5768       17272                1   
3     1961           30900    11117       34350                1   
4     1961           68798     7236       49784                1   
...    ...             ...      ...         ...              ...   
3180  2019           28205   137441      387653                1   
3181  2019          227884    89272     2034364                1   
3182  2019          330348  1016811       30780                1   
3183  2019          491409   201278     9890963                1   
3184  2019          651132    96768     6300864                1   

      Item_Areca nuts  Item_Bananas  Item_Barley  Item_Bastfibres, others  \
0                   1             0            0                        0   
1                   0             1            0                        0   
2                   0             0            1                        0   
3                   0             0            0                        1   
4                   0             0            0                        0   
...               ...           ...          ...                      ...   
3180                0             0            0                        0   
3181                0             0            0                        0   
3182                0             0            0                        0   
3183                0             0            0                        0   
3184                0             0            0                        0   

      Item_Beans, dry  ...  Item_Sugar cane  Item_Sugar crops nes  \
0                   0  ...                0                     0   
1                   0  ...                0                     0   
2                   0  ...                0                     0   
3                   0  ...                0                     0   
4                   1  ...                0                     0   
...               ...  ...              ...                   ...   
3180                0  ...                0                     0   
3181                0  ...                0                     0   
3182                0  ...                0                     0   
3183                0  ...                0                     0   
3184                0  ...                0                     0   

      Item_Sweet potatoes  Item_Tangerines, mandarins, clementines, satsumas  \
0                       0                                                  0   
1                       0                                                  0   
2                       0                                                  0   
3                       0                                                  0   
4                       0                                                  0   
...                   ...                                                ...   
3180                    0                                                  0   
3181                    0                                                  0   
3182                    0                                                  0   
3183                    0                                                  0   
3184                    0                                                  0   

      Item_Tea  Item_Tobacco  Item_Tomatoes  Item_Vegetables Primary  \
0            0             0              0                        0   
1            0             0              0                        0   
2            0             0              0                        0   
3            0             0              0                        0   
4            0             0              0                        0   
...        ...           ...            ..

In [16]:
## k-1 One hot encoding

In [17]:
pd.get_dummies(df,columns=['Area','Item'],drop_first=True)

Year  Area Harvested    Yield  Production  Item_Bananas  Item_Barley  \
0     1961           82600     7627       62995             0            0   
1     1961           33600   132738      446000             1            0   
2     1961           29947     5768       17272             0            1   
3     1961           30900    11117       34350             0            0   
4     1961           68798     7236       49784             0            0   
...    ...             ...      ...         ...           ...          ...   
3180  2019           28205   137441      387653             0            0   
3181  2019          227884    89272     2034364             0            0   
3182  2019          330348  1016811       30780             0            0   
3183  2019          491409   201278     9890963             0            0   
3184  2019          651132    96768     6300864             0            0   

      Item_Bastfibres, others  Item_Beans, dry  Item_Beans, green  \
0                           0                0                  0   
1                           0                0                  0   
2                           0                0                  0   
3                           1                0                  0   
4                           0                1                  0   
...                       ...              ...                ...   
3180                        0                0                  0   
3181                        0                0                  0   
3182                        0                0                  0   
3183                        0                0                  0   
3184                        0                0                  0   

      Item_Berries nes  ...  Item_Sugar cane  Item_Sugar crops nes  \
0                    0  ...                0                     0   
1                    0  ...                0                     0   
2                    0  ...                0                     0   
3                    0  ...                0                     0   
4                    0  ...                0                     0   
...                ...  ...              ...                   ...   
3180                 0  ...                0                     0   
3181                 0  ...                0                     0   
3182                 0  ...                0                     0   
3183                 0  ...                0                     0   
3184                 0  ...                0                     0   

      Item_Sweet potatoes  Item_Tangerines, mandarins, clementines, satsumas  \
0                       0                                                  0   
1                       0                                                  0   
2                       0                                                  0   
3                       0                                                  0   
4                       0                                                  0   
...                   ...                                                ...   
3180                    0                                                  0   
3181                    0                                                  0   
3182                    0                                                  0   
3183                    0                                                  0   
3184                    0                                                  0   

      Item_Tea  Item_Tobacco  Item_Tomatoes  Item_Vegetables Primary  \
0            0             0              0                        0   
1            0             0              0                        0   
2            0             0              0                        0   
3            0             0              0                        0   
4            0             0              0                        0   
...   

In [18]:
## One hot encoding using SK learn

In [19]:
from sklearn.model_selection import train_test_split
# first 5 cols as train as input, last col as output
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:5],df.iloc[:,-1],test_size=0.2,random_state=2)

In [20]:
X_test.head()

Area  Year          Item  Area Harvested  Yield
3064  Bangladesh  2017    Spices nes           47332  35494
761   Bangladesh  1975  Beans, green            6632  39704
2692  Bangladesh  2010           Tea           52236  11486
2940  Bangladesh  2015       Linseed            7009   6941
1901  Bangladesh  1996      Coconuts           29200  30479

In [11]:
from sklearn.preprocessing import OneHotEncoder

In [21]:
# object
# multicollinearity removal
# removing the catagories from the columns with drop first
ohe = OneHotEncoder(drop='first',sparse=False,dtype=np.int32)

In [22]:
X_train_new = ohe.fit_transform(X_train[['Area','Item']])
# we get the no. of cols depending on the categories
X_train_new

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [23]:
X_test_new = ohe.transform(X_test[['Area','Item']])

In [24]:
X_test_new

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]])

In [25]:
# now to append everything together
data = np.hstack((X_train[['Year','Area Harvested','Yield']].values,X_train_new))
data

array([[    2008,    72581,     9856, ...,        0,        0,        0],
       [    2011,   708723,    21494, ...,        0,        0,        0],
       [    1985,    77023,    62181, ...,        0,        1,        0],
       ...,
       [    1990,     4014,    45279, ...,        0,        0,        0],
       [    2008,    46482,     8547, ...,        0,        0,        0],
       [    2008, 11279150,    41441, ...,        0,        0,        0]],
      dtype=int64)

In [26]:
## Random Forest

In [28]:
from sklearn.ensemble import RandomForestClassifier

In [58]:
x = data[:,0:5]
y = data[:,-1]
X_train_new, X_test_new, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [57]:
clf=RandomForestClassifier()
clf.fit(X_train_new, y_train)

RandomForestClassifier()

In [56]:
print (clf.score(X_train_new, y_train))
print(clf.score(X_test_new, y_test))

1.0
0.9823529411764705
